package com.ycw.entity;

public class FeeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.mch_id
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.device_info
     *
     * @mbggenerated
     */
    private String deviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.nonce_str
     *
     * @mbggenerated
     */
    private String nonceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.sign_type
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.attach
     *
     * @mbggenerated
     */
    private String attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.fee_type
     *
     * @mbggenerated
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.total_fee
     *
     * @mbggenerated
     */
    private Double totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.spbill_create_ip
     *
     * @mbggenerated
     */
    private String spbillCreateIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.time_start
     *
     * @mbggenerated
     */
    private String timeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.time_expire
     *
     * @mbggenerated
     */
    private String timeExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.goods_tag
     *
     * @mbggenerated
     */
    private String goodsTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.notify_url
     *
     * @mbggenerated
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.limit_pay
     *
     * @mbggenerated
     */
    private String limitPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.scene_info
     *
     * @mbggenerated
     */
    private String sceneInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_feeinfo.oreder_status
     *
     * @mbggenerated
     */
    private String orederStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.id
     *
     * @return the value of w_feeinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.id
     *
     * @param id the value for w_feeinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.appid
     *
     * @return the value of w_feeinfo.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.appid
     *
     * @param appid the value for w_feeinfo.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.mch_id
     *
     * @return the value of w_feeinfo.mch_id
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.mch_id
     *
     * @param mchId the value for w_feeinfo.mch_id
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.device_info
     *
     * @return the value of w_feeinfo.device_info
     *
     * @mbggenerated
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.device_info
     *
     * @param deviceInfo the value for w_feeinfo.device_info
     *
     * @mbggenerated
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo == null ? null : deviceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.nonce_str
     *
     * @return the value of w_feeinfo.nonce_str
     *
     * @mbggenerated
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.nonce_str
     *
     * @param nonceStr the value for w_feeinfo.nonce_str
     *
     * @mbggenerated
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr == null ? null : nonceStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.sign
     *
     * @return the value of w_feeinfo.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.sign
     *
     * @param sign the value for w_feeinfo.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.sign_type
     *
     * @return the value of w_feeinfo.sign_type
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.sign_type
     *
     * @param signType the value for w_feeinfo.sign_type
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.body
     *
     * @return the value of w_feeinfo.body
     *
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.body
     *
     * @param body the value for w_feeinfo.body
     *
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.detail
     *
     * @return the value of w_feeinfo.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.detail
     *
     * @param detail the value for w_feeinfo.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.attach
     *
     * @return the value of w_feeinfo.attach
     *
     * @mbggenerated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.attach
     *
     * @param attach the value for w_feeinfo.attach
     *
     * @mbggenerated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.out_trade_no
     *
     * @return the value of w_feeinfo.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.out_trade_no
     *
     * @param outTradeNo the value for w_feeinfo.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.fee_type
     *
     * @return the value of w_feeinfo.fee_type
     *
     * @mbggenerated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.fee_type
     *
     * @param feeType the value for w_feeinfo.fee_type
     *
     * @mbggenerated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType == null ? null : feeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.total_fee
     *
     * @return the value of w_feeinfo.total_fee
     *
     * @mbggenerated
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.total_fee
     *
     * @param totalFee the value for w_feeinfo.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.spbill_create_ip
     *
     * @return the value of w_feeinfo.spbill_create_ip
     *
     * @mbggenerated
     */
    public String getSpbillCreateIp() {
        return spbillCreateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.spbill_create_ip
     *
     * @param spbillCreateIp the value for w_feeinfo.spbill_create_ip
     *
     * @mbggenerated
     */
    public void setSpbillCreateIp(String spbillCreateIp) {
        this.spbillCreateIp = spbillCreateIp == null ? null : spbillCreateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.time_start
     *
     * @return the value of w_feeinfo.time_start
     *
     * @mbggenerated
     */
    public String getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.time_start
     *
     * @param timeStart the value for w_feeinfo.time_start
     *
     * @mbggenerated
     */
    public void setTimeStart(String timeStart) {
        this.timeStart = timeStart == null ? null : timeStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.time_expire
     *
     * @return the value of w_feeinfo.time_expire
     *
     * @mbggenerated
     */
    public String getTimeExpire() {
        return timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.time_expire
     *
     * @param timeExpire the value for w_feeinfo.time_expire
     *
     * @mbggenerated
     */
    public void setTimeExpire(String timeExpire) {
        this.timeExpire = timeExpire == null ? null : timeExpire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.goods_tag
     *
     * @return the value of w_feeinfo.goods_tag
     *
     * @mbggenerated
     */
    public String getGoodsTag() {
        return goodsTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.goods_tag
     *
     * @param goodsTag the value for w_feeinfo.goods_tag
     *
     * @mbggenerated
     */
    public void setGoodsTag(String goodsTag) {
        this.goodsTag = goodsTag == null ? null : goodsTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.notify_url
     *
     * @return the value of w_feeinfo.notify_url
     *
     * @mbggenerated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.notify_url
     *
     * @param notifyUrl the value for w_feeinfo.notify_url
     *
     * @mbggenerated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.trade_type
     *
     * @return the value of w_feeinfo.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.trade_type
     *
     * @param tradeType the value for w_feeinfo.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.product_id
     *
     * @return the value of w_feeinfo.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.product_id
     *
     * @param productId the value for w_feeinfo.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.limit_pay
     *
     * @return the value of w_feeinfo.limit_pay
     *
     * @mbggenerated
     */
    public String getLimitPay() {
        return limitPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.limit_pay
     *
     * @param limitPay the value for w_feeinfo.limit_pay
     *
     * @mbggenerated
     */
    public void setLimitPay(String limitPay) {
        this.limitPay = limitPay == null ? null : limitPay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.openid
     *
     * @return the value of w_feeinfo.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.openid
     *
     * @param openid the value for w_feeinfo.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.scene_info
     *
     * @return the value of w_feeinfo.scene_info
     *
     * @mbggenerated
     */
    public String getSceneInfo() {
        return sceneInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.scene_info
     *
     * @param sceneInfo the value for w_feeinfo.scene_info
     *
     * @mbggenerated
     */
    public void setSceneInfo(String sceneInfo) {
        this.sceneInfo = sceneInfo == null ? null : sceneInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_feeinfo.oreder_status
     *
     * @return the value of w_feeinfo.oreder_status
     *
     * @mbggenerated
     */
    public String getOrederStatus() {
        return orederStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_feeinfo.oreder_status
     *
     * @param orederStatus the value for w_feeinfo.oreder_status
     *
     * @mbggenerated
     */
    public void setOrederStatus(String orederStatus) {
        this.orederStatus = orederStatus == null ? null : orederStatus.trim();
    }
}