package com.ycw.entity;

public class Diary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.ctime
     *
     * @mbggenerated
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.stime
     *
     * @mbggenerated
     */
    private String stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.okstatus
     *
     * @mbggenerated
     */
    private Integer okstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.datastatus
     *
     * @mbggenerated
     */
    private Integer datastatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.id
     *
     * @return the value of diary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.id
     *
     * @param id the value for diary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.content
     *
     * @return the value of diary.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.content
     *
     * @param content the value for diary.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.ctime
     *
     * @return the value of diary.ctime
     *
     * @mbggenerated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.ctime
     *
     * @param ctime the value for diary.ctime
     *
     * @mbggenerated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.stime
     *
     * @return the value of diary.stime
     *
     * @mbggenerated
     */
    public String getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.stime
     *
     * @param stime the value for diary.stime
     *
     * @mbggenerated
     */
    public void setStime(String stime) {
        this.stime = stime == null ? null : stime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.okstatus
     *
     * @return the value of diary.okstatus
     *
     * @mbggenerated
     */
    public Integer getOkstatus() {
        return okstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.okstatus
     *
     * @param okstatus the value for diary.okstatus
     *
     * @mbggenerated
     */
    public void setOkstatus(Integer okstatus) {
        this.okstatus = okstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.datastatus
     *
     * @return the value of diary.datastatus
     *
     * @mbggenerated
     */
    public Integer getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.datastatus
     *
     * @param datastatus the value for diary.datastatus
     *
     * @mbggenerated
     */
    public void setDatastatus(Integer datastatus) {
        this.datastatus = datastatus;
    }

	@Override
	public String toString() {
		return "Diary [id=" + id + ", content=" + content + ", ctime=" + ctime + ", stime=" + stime + ", okstatus="
				+ okstatus + ", datastatus=" + datastatus + "]";
	}
}