package com.ycw.dao;

import com.ycw.entity.Diary;
import com.ycw.entity.DiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int countByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int deleteByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    List<Diary> selectByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    Diary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Diary record);
}