package com.ycw.dao;

import com.ycw.entity.FeeInfo;
import com.ycw.entity.FeeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int countByExample(FeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int deleteByExample(FeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int insert(FeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int insertSelective(FeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    List<FeeInfo> selectByExample(FeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    FeeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FeeInfo record, @Param("example") FeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FeeInfo record, @Param("example") FeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_feeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FeeInfo record);
}